# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c064b287fd0c656ee14d1eee39c66f7ba53c7881c793fd31628fb98a3765da9fb2bb97acae65f3e3458b5e74903a69af6f5fe67ca19c42c96ae8161d86596569

test:
  secret_key_base: 6cbc98957037eb9e2770e727f5832058ece95cfb212cdd4eb800d903410b7e390c5c54ed4b00335281ddd56ca11402a04ddf61526615717215bbee013f2a80d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
